name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Build
        run: cargo build --verbose --verbose
    
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Run Tests
        run: cargo test --verbose --verbose

      - name: Check Format
        run: cargo fmt --all -- --check
  
  coverage:
    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - uses: actions/checkout@v3

      - name: Generate code coverage
        run: cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
